apiVersion: apps/v1
kind: Deployment

metadata:
  name: journey-deployment
  labels:
    app: journey

spec:
  replicas: 5
  selector:
    matchLabels:
      app: journey
  template:
    metadata:
      labels:
        app: journey
    spec:
      containers:
        - name: api-journey
          image: api-journey:75e09f8
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: journey-secret
                  key: DATABASE_URL
            - name: API_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: journey-secret
                  key: API_BASE_URL
            - name: WEB_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: journey-secret
                  key: WEB_BASE_URL
            - name: EMAIL_CONNECTION_URL
              valueFrom:
                secretKeyRef:
                  name: journey-secret
                  key: EMAIL_CONNECTION_URL
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
