CREATE TABLE trips (
    id UUID NOT NULL PRIMARY KEY DEFAULT gen_random_uuid(),
    destination TEXT NOT NULL,
    starts_at TIMESTAMP NOT NULL,
    ends_at TIMESTAMP NOT NULL,
    is_confirmed BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)
