name: CI

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    name: "Build and Push"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run tests
        run: cargo test -r

      - name: Generate SHA
        id: generate_sha
        run: |
          SHA=$(echo $GITHUB_SHA | head -c 7)
          echo "SHA=$SHA" >> $GITHUB_ENV

      # - name: Login to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Build and push
      #   uses: docker/build-push-action@v6
      #   with:
      #     context: .
      #     push: true
      #     tags: |
      #       ${{ secrets.DOCKERHUB_USERNAME }}/api-journey:${{ steps.generate_sha.outputs.sha }}
      #       ${{ secrets.DOCKERHUB_USERNAME }}/api-journey:latest
